---
- name: install sssd with ldap support
  package:
    name:
      - sssd
      - sssd-ldap
    state: present
  tags: [ sssd-install ]

- name: template sssd.conf
  template:
    src: sssd.conf.gentoo.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart sssd
  tags : [ sssd-config ]

- name: Make home directory
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0022'
  notify: restart sssd
  tags: [ sssd-config ]

- name: start sssd on boot
  service: name=sssd state=started enabled=yes

